### ISSUE TITLE
Django 4.1 support

### ISSUE THREAD

**Issue by tonisvain** [dinoperovic/django-salesman-stripe#3]
django-salesman supports Django 4.1

as far as i have used it, it seems to work as is with Django 4.1, but i have not actually checked this against the 4.1 release notes.

**Comment by dinoperovic** [comment]
Hi @tonisvain, since this package doesn't deal with Django much and mostly only adds the Salesman-related stuff, I would say it's pretty safe to use with 4.1.

Of course do the tests, but if it runs, should be good.

I currently don't have much time to test this, but I am planning on supporting 4.1. and beyond if the issues are presented.

**Comment by madisvain** [comment]
@dinoperovic we have not had any issues running it on Django 4.1. I think the issue that Tõnis was trying to raise is that the pyproject limits it to <4.1 and thats why it can not be installed easily.

Could we ease these limitations? https://github.com/dinoperovic/django-salesman-stripe/blob/master/pyproject.toml#L30

**Comment by dinoperovic** [comment]
@madisvain yes sure, this is actually a mistake as the requirements should mirror `django-salesman` ones. We can do away with the Django version cap in these payment packages. I will look to remove it.

**Comment by dinoperovic** [comment]
Fixed in `v0.1.6`
